version: 2
jobs:
  build-node10:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: rebuild
          command: npm rebuild
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  build-node11:
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: rebuild
          command: npm rebuild
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  build-node12:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: rebuild
          command: npm rebuild
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build-node10
      - build-node11
      - build-node12